spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ENC(gLXsx1Y/9rik+LTEsAPz5wCGrrSfPsDyK9JugW0uxs1oBzVFph6Xd1zxA/xIJbnBpWe0+8/y1iMQM/QbXwhW8o4CZYTHas7KxsfAjs4ekwEVAZ0BEG101JqhSm557qVv)
    username: ENC(5PhD0hS4AvuUt4PpBrybvg==)
    password: ENC(IenfY1uoKmAXZIcp0ac0KSvXThBMExLj)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor