spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ENC(uhhRtpbqmYlaQj+5+7MEvZ9Qgv+v68dNESPpc/FBvUjICpgaHNRseVaCp+nCWdvxJ3g5KVTy3cxupMAI178IY7C9WGjgq9svchPJbh8aDzh0+4dyxlLomNlwGovecf37)
    username: ENC(gbBHw8hlQ7p1hjGhsVzLpQleoLHsdzom)
    password: ENC(o3Lp+SQGWUk5eOtk6WT0h4MGxVQuGQIH)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor